name: Deploy React Book App from GitHub to AWS Elastic Beanstalk
on:
  # activates the workflow when there is a push on the main branch
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest # the OS your job should run on
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Latest Repo
        # checks out your repository under the GitHub workspace so that your workflow can access it
        uses: actions/checkout@v2

      - name: Generate Deployment Package 
        # zip all files except .git
        run: zip -r SplitBillUI.zip * -x "**.git**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
         #  input the credentials you used to setup AWS CLI and credentials for the application environment
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          application_name: splitApp
          environment_name: splitApp-env
          version_label:  "ver-${{ github.sha }}" 
          region: us-east-1
          deployment_package: SplitBillUI.zip

      - name: Deployed!
        run: echo App deployed to ELB